CREATE TABLE  IF NOT EXISTS `#queue name#` (
	`msgId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`content` TEXT NOT NULL,
	`client` VARCHAR(128) NOT NULL,
	`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`msgId`),
	INDEX `CREATE_TIME` (`createTime`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE IF NOT EXISTS `Receipt` (
	`client` VARCHAR(128) NOT NULL,
	`queue` VARCHAR(128) NOT NULL,
	`msgId` BIGINT(20) NOT NULL,
	`updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`client`, `queue`),
	INDEX `updateTime` (`updateTime`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;